### ISSUE TITLE
更改工作流1h运行一次仓库有更改会输出信息并提交，无更改则不会提交会继续运行完成，不会输出错误信息（Github邮件提醒很烦人），大佬们瞅瞅对不对

### ISSUE THREAD

**Issue by wxmbot** [vveg26/chromego_merge#29]
```
name: Merge Script

on:
  # push:
  #   branches:
  #     - main  # 替换为你的默认分支
  schedule:
    - cron: '0 * * * *'  # 每1h一次
  workflow_dispatch:  # 触发手动事件
jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11  

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run merge script
        run: python meta_merge.py 

      - name: Run shadowrocket merge script
        run: python merge.py  

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected in the repository."
            git config core.ignorecase false
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Updated at $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes detected in the repository."
          fi
```
